alias: 🍽️ Lave-Vaisselle - Gestion Cycle & Notifications (Simple)
description: "Gestion du cycle et notification persistante (Version Simple)"
mode: restart
triggers:
  # 1. DÉMARRAGE : Quand la puissance dépasse le seuil (via le binary_sensor)
  - trigger: state
    entity_id: binary_sensor.lave_vaisselle_en_marche
    from: "off"
    to: "on"
    id: "demarrage"
  # 2. FIN : Quand la puissance repasse sous le seuil
  - trigger: state
    entity_id: binary_sensor.lave_vaisselle_en_marche
    from: "on"
    to: "off"
    id: "fin"
  # 3. REDÉMARRAGE HA : Pour relancer la boucle de notification si le cycle était "Terminé"
  - trigger: homeassistant
    event: start
    id: "redemarrage"
conditions: []
actions:
  - choose:
      # CAS A : DÉMARRAGE
      # On initialise tout : Reset compteur kWh, État=En marche, Heure de début.
      - conditions:
          - condition: trigger
            id: "demarrage"
        sequence:
          - action: utility_meter.reset
            target:
              entity_id: sensor.compteur_lave_vaisselle_cycle
          - action: input_select.select_option
            target:
              entity_id: input_select.etat_lave_vaisselle
            data:
              option: "En marche"
          - action: input_datetime.set_datetime
            target:
              entity_id: input_datetime.debut_lave_vaisselle
            data:
              datetime: "{{ now() }}"

      # CAS B : FIN DU CYCLE
      # On valide la fin : État=Terminé, Heure de fin.
      - conditions:
          - condition: trigger
            id: "fin"
        sequence:
          - action: input_select.select_option
            target:
              entity_id: input_select.etat_lave_vaisselle
            data:
              option: "Terminé"
          - action: input_datetime.set_datetime
            target:
              entity_id: input_datetime.fin_lave_vaisselle
            data:
              datetime: "{{ now() }}"

      # CAS C : REDÉMARRAGE HA
      # Sécurité : On attend que les entités soient prêtes pour éviter les erreurs de lecture.
      - conditions:
          - condition: trigger
            id: "redemarrage"
        sequence:
          # On attend que les entités soient disponibles
          - wait_template: >-
              {{ has_value('input_select.etat_lave_vaisselle') and 
                 has_value('switch.prislavvais') }} # [A_CHANGER] Remplacez par votre prise connectée
            timeout: "00:05:00"
            continue_on_timeout: false

  # BOUCLE DE NOTIFICATION (COMMUNE)
  - if:
      - condition: state
        entity_id: input_select.etat_lave_vaisselle
        state: "Terminé"
      - condition: state
        # [A_CHANGER] Remplacez par votre prise connectée
        entity_id: switch.prislavvais
        state: "on"
    then:
      - repeat:
          sequence:
            - action: persistent_notification.create
              data:
                message: |
                  Cycle terminé.
                  Durée : {{ states('sensor.lave_vaisselle_duree_cycle') }}
                  Conso : {{ states('sensor.compteur_lave_vaisselle_cycle') }} kWh
                  Coût : {{ states('sensor.lave_vaisselle_cout_cycle') }} €
                title: "🍽️ Lave-Vaisselle Terminé"
                notification_id: "lave_vaisselle_fin"

            - delay:
                hours: 0
                minutes: 5
                seconds: 0
                milliseconds: 0

          while:
            - condition: state
              # [A_CHANGER] La boucle s'arrête si la prise est éteinte
              entity_id: switch.prislavvais
              state: "on"
